---
exp_name: METR_LA
exp_dir: ./exp/METR_LA
use_gpu: True
device: 0
seed: 1010

model_name: GTS

graph_learning_module: GTS
graph_forecasting_module: GTS
initial_edge_index: Fully Connected

dataset:
  root: ./data/METR-LA
  name: METR-LA
  graph_learning_length: 34272
  pred_step: 1

train:
  optimizer: Adam
  epoch: 50
  loss_function : MAE
  lr: 1.0e-3
  momentum: 0.9
  wd: 0.0e-4
  batch_size : 2
  lr_decay: 0.1
  lr_decay_steps: [10000]

nodes_num: 207
node_features: 1
hidden_dim: 32
embedding_dim: 1

graph_learning:
  sequence: 1
  mode: adj # adj, weight
  to_symmetric: True
  correlation_act_fnc: sigmoid # softmax, relu ...
  kernel_size: [200, 100, 50]
  stride: [20, 10, 5]
  conv1_dim: 16
  conv2_dim: 32
  conv3_dim: 64
  n_head: 4
#  fc_dim: 256


forecasting_module:
  diffusion_k: 2
  num_layer: 1
  use_teacher_forcing: True
  teacher_forcing_ratio: 0.5

encoder_step: 12
decoder_step: 3

tau: 0.3



