---
exp_name: METR_LA
exp_dir: ./exp/METR_LA
use_gpu: True
device: 0
seed: 1010

model_name: GTS

graph_learning_module: GTS
graph_forecasting_module: GTS
initial_edge_index: Fully Connected

dataset:
  root: ./data/METR-LA
  name: METR-LA
  graph_learning_length: 34272
  pred_step: 1

train:
  optimizer: Adam
  epoch: 50
  loss_function : MAE
  lr: 1.0e-2
  momentum: 0.9
  wd: 0.0e-4
  batch_size : 32
  lr_decay: 0.1
  lr_decay_steps: [10000]

nodes_num: 207
node_features: 2
hidden_dim: 64
encoder_embedding_dim: 2
decoder_embedding_dim: 1

graph_learning:
  sequence: 1
  mode: attention # GTS, attention
  sampling: True # True: Gumbel softmax, False: No Sampling -> Use like Weight matrix
  to_symmetric: False
  kernel_size: [10, 10]
  stride: [1, 1]
  conv_dim: [8, 16]
  n_head: 4
  hidden_dim: 256


forecasting_module:
  diffusion_k: 2
  num_layer: 1
  use_teacher_forcing: True
  teacher_forcing_ratio: 0.5

encoder_step: 12
decoder_step: 3

tau: 0.3



