batch_size: 2
conv1_dim: 8
conv2_dim: 16
dataset:
  name: monkey_data
  root: ./data/CCN/monkey_spike.pickle
  slide: 53
  total_time_length: 742
  train_valid_test:
  - 80
  - 90
  - 100
  window_size: 212
device: cpu
diffusion_k: 3
embedding_dim: 128
encoder_length: 11
exp_dir: ./exp/GTS_test_1217_170551
exp_name: GTS_test_1217_170551
fc_dim: 1312
hidden_dim: 64
kernel_size: 212
model_name: GTS
model_save: ./exp/GTS_test_1217_170551/model_save
node_features: 1
nodes_num: 98
num_layer: 1
output_dim: 1
seed: 1010
stride: 1
train:
  batch_size: 8
  epoch: 2
  loss_function: MSELoss
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  momentum: 0.9
  optimizer: Adam
  wd: 0.0
use_gpu: false
