---
exp_name: 0425 # 0417
exp_dir: ../exp
use_gpu: True
device: 0
seed: 1010
model_name: ground_truth  # GTS_Top_k_Masking_model, ...

nodes_num: 207
node_features: 2
hidden_dim: 32
encoder_embedding_dim: 2
decoder_embedding_dim: 1
encoder_step: 12
decoder_step: 3

dataset:
  root: ./data/METR-LA
  name: METR-LA
  graph_learning_length: 34272
  pred_step: 1

train:
  optimizer: Adam
  epoch: 100
  loss_function : MAE
  lr: 1.0e-3
  momentum: 0.9
  wd: 0.0e-4
  batch_size : 128
  lr_decay: 0.1
  lr_decay_steps: [10000]

graph_learning:
  mode: None # GTS, attention, MTGNN, GDN, None
  graph_mode: ground_truth # no_graph, ground_truth
  edge_prob: 0.01 # Use this probability when graph_mode is random_graph

  sampling: None # Gumbel_softmax, Top_k_Masking, , Top_K, Weight, None
  tau: 10
  top_k: 10
  alpha: 200
  to_symmetric: False
  initial_edge_index: Fully Connected
  sequence: 1

  kernel_size: [10, 10]
  stride: [1, 1]
  conv_dim: [8, 16]
  n_head: 4
  hidden_dim: 128


forecasting_module:
  diffusion_k: 2
  num_layer: 1
  use_teacher_forcing: True
  teacher_forcing_ratio: 0.5



