batch_size: 2
conv1_dim: 8
conv2_dim: 16
dataset:
  name: spike_lambda
  root: ./data/spike_lambda
decoder_length: 20
device: cpu
diffusion_k: 3
encoder_length: 200
exp_dir: ./exp/GTS_1_1215_021047
exp_name: GTS_1_1215_021047
fc_dim: 1312
hidden_dim: 64
kernel_size: 10
model_name: GTS
model_save: ./exp/GTS_1_1215_021047/model_save
node_features: 1
nodes_num: 100
num_layer: 1
output_dim: 1
seed: 1010
stride: 1
tau: 0.3
teacher_forcing_ratio: 0.5
train:
  batch_size: 64
  epoch: 100
  loss_function: MSELoss
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  momentum: 0.9
  optimizer: Adam
  wd: 0.0
use_gpu: false
use_teacher_forcing: true
