---
exp_name: 1
exp_dir: ./exp
use_gpu: True
device: 1
seed: 10101
model_name: GTS

dataset:
  root: ./data/spike_lambda
  name: spike_lambda
#  time_steps: 10
#  pred_steps: 2
#  window: 100
#  train_step: 400
#  validation_step: 440
#  test_step: 480

train:
  optimizer: Adam
  epoch: 10
  loss_function : MSELoss
  lr: 1.0e-3
  momentum: 0.9
  wd: 0.0e-4
  batch_size : 128
  lr_decay: 0.1
  lr_decay_steps: [10000]


node_features: 1
output_dim: 1
hidden_dim: 64
nodes_num: 100

kernel_size: 10
stride: 1
conv1_dim: 8
conv2_dim: 16
fc_dim: 1312

diffusion_k: 3
num_layer: 1

encoder_length: 200
decoder_length: 20

tau: 0.3
use_teacher_forcing: True
teacher_forcing_ratio: 0.5


