---
exp_name: 1
exp_dir: ./exp
use_gpu: False
device: cpu
seed: 1010

model_name: GTS

graph_learning_module: GTS
graph_forecasting_module: GTS

dataset:
  root: ./data/spike_lambda_bin100
  name: spike_lambda_bin100
  total_time_length: 48000
  idx_ratio: 0.5
  window_size: 200
  slide: 50
  pred_step: 50

  train_valid_test: [40000,44000,48000]
  save: ./data/spike_lambda_bin100/


train:
  optimizer: Adam
  epoch: 1
  loss_function : MSELoss
  lr: 1.0e-3
  momentum: 0.9
  wd: 0.0e-4
  batch_size : 64
  lr_decay: 0.1
  lr_decay_steps: [10000]

nodes_num: 100
node_features: 1
hidden_dim: 64
embedding_dim: 128

graph_learning:
  to_symmetric: True
  kernel_size: [200, 100, 50]
  stride: [20, 10, 5]
  conv1_dim: 8
  conv2_dim: 16
  conv3_dim: 64
#  fc_dim: 256


forecasting_module:
  diffusion_k: 3
  num_layer: 1
  use_teacher_forcing: True
  teacher_forcing_ratio: 0.5

  embedding:
    kernel_size: [10, 10]
    stride: [3, 3]
    conv1_dim: 8
    conv2_dim: 16
#    fc_dim: 128

batch_size: 2
encoder_step: 10
decoder_step: 3

tau: 0.3



