---
exp_name: 1
exp_dir: ./exp
use_gpu: False
device: cpu
seed: 1010

model_name: GTS

graph_learning_module: GTS
graph_forecasting_module: GTS
initial_edge_index: Fully Connected

dataset:
  root: ./data/spike_lambda_bin100
  name: spike_lambda_bin100
  total_time_length: 4800
  idx_ratio: 0.5
  window_size: 20
  slide: 5
  pred_step: 5

  train_valid_test: [4000,4400,4800]
  save: ./data/spike_lambda_bin100/


train:
  optimizer: Adam
  epoch: 2
  loss_function : MSELoss
  lr: 1.0e-3
  momentum: 0.9
  wd: 0.0e-4
  batch_size : 1
  lr_decay: 0.1
  lr_decay_steps: [10000]

nodes_num: 100
node_features: 1
hidden_dim: 16
embedding_dim: 16

graph_learning:
  to_symmetric: True
  kernel_size: [200, 80, 10]
  stride: [20, 10, 5]
  conv1_dim: 4
  conv2_dim: 4
  conv3_dim: 4
#  fc_dim: 256


forecasting_module:
  diffusion_k: 1
  num_layer: 1
  use_teacher_forcing: True
  teacher_forcing_ratio: 0.5

  embedding:
    kernel_size: [3, 3]
    stride: [1, 1]
    conv1_dim: 2
    conv2_dim: 2
#    fc_dim: 128

encoder_step: 2
decoder_step: 2

tau: 0.3



