device: cpu
seed: 1010

dataset:
  name: spike_lambda
  time_stpes: 200
  pred_steps: 20
  window_size: 2
  batch_size : 128



loss : MSELoss

node_features: 1
output_dim: 1
hidden_dim: 64
nodes_num: 30

kernel_size: 10
stride: 1
conv1_dim: 8
conv2_dim: 16
fc_dim: 15712

diffusion_k: 3
num_layer: 1

batch_size: 128
encoder_length: 70
decoder_length: 30

tau: 0.3
use_teacher_forcing: False
teacher_forcing_ratio: 0.5


