batch_size: 2
dataset:
  idx_ratio: 0.5
  name: spike_lambda_bin100
  pred_step: 50
  root: ./data/spike_lambda_bin100
  save: ./data/spike_lambda_bin100/
  slide: 50
  total_time_length: 48000
  train_valid_test:
  - 40000
  - 44000
  - 48000
  window_size: 200
decoder_step: 3
device: cpu
embedding_dim: 128
encoder_step: 10
exp_dir: ./exp\GTS_1_0110_043239
exp_name: GTS_1_0110_043239
forecasting_module:
  diffusion_k: 3
  embedding:
    conv1_dim: 8
    conv2_dim: 16
    kernel_size:
    - 10
    - 10
    stride:
    - 3
    - 3
  num_layer: 1
  teacher_forcing_ratio: 0.5
  use_teacher_forcing: true
graph_forecasting_module: GTS
graph_learning:
  conv1_dim: 8
  conv2_dim: 16
  conv3_dim: 64
  kernel_size:
  - 200
  - 100
  - 50
  stride:
  - 20
  - 10
  - 5
  to_symmetric: true
graph_learning_module: GTS
hidden_dim: 64
model_name: GTS
model_save: ./exp\GTS_1_0110_043239\model_save
node_features: 1
nodes_num: 100
seed: 1010
tau: 0.3
train:
  batch_size: 64
  epoch: 1
  loss_function: MSELoss
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  momentum: 0.9
  optimizer: Adam
  wd: 0.0
use_gpu: false
