batch_size: 128
conv1_dim: 8
conv2_dim: 16
dataset:
  name: spike_lambda
  pred_steps: 20
  root: ./data/spike_lambda
  test_step: 4800
  time_steps: 500
  train_step: 4000
  validation_step: 4400
  window: 100
decoder_length: 30
device: cpu
diffusion_k: 3
encoder_length: 70
exp_dir: ./exp/GTS_1_1214_181341
exp_name: GTS_1_1214_181341
fc_dim: 15712
hidden_dim: 16
kernel_size: 10
model_name: GTS
model_save: ./exp/GTS_1_1214_181341/model_save
node_features: 1
nodes_num: 100
num_layer: 1
output_dim: 1
seed: 1010
stride: 1
tau: 0.3
teacher_forcing_ratio: 0.5
train:
  batch_size: 128
  epoch: 1
  loss_function: MSELoss
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  momentum: 0.9
  optimizer: Adam
  wd: 0.0
use_gpu: false
use_teacher_forcing: false
