conv1_dim: 16
conv2_dim: 64
dataset:
  name: monkey_data
  root: ./data/CCN/monkey_spike.pickle
  slide: 54
  total_time_length: 742
  train_valid_test:
  - 80
  - 90
  - 100
  window_size: 202
decode_dim: 3
decode_step: 54
device: cpu
diffusion_k: 3
embedding:
  conv_dim:
  - 8
  - 16
  embedding_dim: 16
  hidden_state: 16
  kernel_size:
  - 30
  - 15
  stride:
  - 10
  - 5
exp_dir: ./exp/GTS_test_1222_173810
exp_name: GTS_test_1222_173810
fc_dim: 128
hidden_dim: 128
kernel_size:
- 100
- 50
- 4
loss_ratio: 0.5
model_name: GTS
model_save: ./exp/GTS_test_1222_173810/model_save
node_features: 1
nodes_num: 98
num_layer: 1
output_dim: 3
seed: 1010
stride:
- 10
- 5
- 1
train:
  batch_size: 1
  epoch: 1
  loss_function: MSELoss
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  momentum: 0.9
  optimizer: Adam
  wd: 0.0
use_gpu: false
