---
exp_name: METR_LA/Random_2 # 0417
exp_dir: ../exp
use_gpu: True
device: 0
seed: None # If you want to reproduce set the seed
model_name: IC_PN_BEATS
train_resume: False

dataset:
    name: METR-LA # ETTm1, ETTm2, ETTh1, ETTh2, ECL, WTH, Traffic, COVID19, METR-LA, PEMS-BAY, Exchange
    scaler_type: std # std, invariant, norm, norm1, median
    univariate: True

train:
    optimizer: Adam
    epoch: 200
    loss_function : MAE
    backcast_loss: False
    lr: 1.0e-3
    wd: 0.0e-4 # Adam
    momentum: 0.9 # SGD
    T_0: 50 # cosine annealing
    T_mult: 5 # cosine annealing
    batch_size : 64

graph_learning:
    graph_learning: False
    # This Parameters is available when graph_learning is False
    graph_mode: random_graph # no_graph, ground_truth -> Only available For METR-LA, PEMS-BAY dataset
    edge_prob: 0.05 # For random_graph

    factor: 3 # Use it when Graph learning mode is ProbSparse Attention -> # of sampling Key and Query
    n_head: 4 # Use it Attention Graph Learning
    dropout_rate: 0.5

    kernel_size: [2, 2]
    stride: [2, 2]
    conv_dim: [2, 2]
    hidden_dim: 4

forecasting_module:
    name: pn_beats
    stack_num: 1
    singular_stack_num: 1
    inter_correlation_block_type: MPGLU # GCN, MPNN, MPGLU, MP_single_message, MPGLU_single_message
    update_only_message: True
    activ: ReLU
    inter_correlation_stack_length: 1
    embedding_dim: 256
    forecast_length: 3
    backcast_length: 12
    n_theta_hidden: [12]
    thetas_dim: [4, 4]
    message_norm: True
    pooling_mode: average
    n_pool_kernel_size: [1]
    n_stride_size : [1]
