---
exp_name: exp_name
exp_dir: ../exp
use_gpu: False
device: cpu
seed: 1010
model_name: model_name

nodes_num: 207
node_features: 2
hidden_dim: 32
encoder_embedding_dim: 2
decoder_embedding_dim: 1
encoder_step: 12
decoder_step: 3

dataset:
  root: ./data/METR-LA
  name: METR-LA
  graph_learning_length: 34272
  pred_step: 1

train:
  optimizer: Adam
  epoch: 2
  loss_function : MAE
  lr: 1.0e-3
  momentum: 0.9
  wd: 0.0e-4
  batch_size : 2
  lr_decay: 0.1
  lr_decay_steps: [10000]

graph_learning:
  mode: GTS # GTS, attention, MTGNN, GDN
  sampling: Gumbel_softmax # Gumbel_softmax, Top_k_Masking, , Top_KNone
  tau: 10
  top_k: 10
  alpha: 200
  to_symmetric: False
  initial_edge_index: Fully Connected
  sequence: 1

  kernel_size: [10, 10]
  stride: [1, 1]
  conv_dim: [8, 16]
  n_head: 4
  hidden_dim: 128


forecasting_module:
  diffusion_k: 2
  num_layer: 1
  use_teacher_forcing: True
  teacher_forcing_ratio: 0.5



