---
exp_name: 0729_ECL_EXP # 0417
exp_dir: ../exp
use_gpu: False
device: cpu
seed: None # If you want to reproduce set the seed
model_name: IC_PN_BEATS
train_resume: False

dataset:
    name: ETTm2 # ETTm1, ETTm2, ETTh1, ETTh2, ECL, WTH, Traffic, COVID19, METR-LA, PEMS-BAY, Exchange
    scaler_type: std # std, invariant, norm, norm1, median
    univariate: True

train:
    optimizer: Adam
    epoch: 1
    loss_function : MAE
    backcast_loss: False
    lr: 1.0e-3
    wd: 0.0e-4 # Adam
    momentum: 0.9 # SGD
    T_0: 50 # cosine annealing
    T_mult: 5 # cosine annealing
    batch_size : 16

graph_learning:
    factor: 1 # Use it when Graph learning mode is ProbSparse Attention -> # of sampling Key and Query
    n_head: 1 # Use it Attention Graph Learning
    dropout_rate: 0.5

    kernel_size: [16, 16]
    stride: [2, 2]
    conv_dim: [8, 16]
    hidden_dim: 128

forecasting_module:
    name: pn_beats
    stack_num: 1
    singular_stack_num: 1
    inter_correlation_block_type: MPGLU # GCN, MPNN, MPGLU, MP_single_message, MPGLU_single_message
    activ: ReLU
    inter_correlation_stack_length: 1
    forecast_length: 96
    backcast_length: 96
    n_theta_hidden: [4, 4]
    thetas_dim: [4, 4]
    message_norm: True
    pooling_mode: average
    n_pool_kernel_size: [2]
    n_stride_size : [2]
