---
exp_name: 0517_N_BEATS # 0417
exp_dir: ../exp
use_gpu: False
device: cpu
seed: None # If you want to reproduce set the seed that you want
model_name: N_BEATS_generic  # GTS_Top_k_Masking_model, ...
train_resume: False

dataset:
    root: ./data/ECL # METR-LA, PEMS-BAY, ECL
    name: ECL
    nodes_num: 321 # 207, 321
    node_features: 5 # 2, 5
    scaler_type: std # std, invariant, norm, norm1, median

train:
    optimizer: Adam
    epoch: 1
    loss_function : MAE
    backcast_loss: False
    lr: 1.0e-3
    wd: 0.0e-4 # Adam
    momentum: 0.9 # SGD
    T_0: 50 # cosine annealing
    T_mult: 5 # cosine annealing
    batch_size : 128

graph_learning:
    factor: 2 # Use it when Graph learning mode is ProbSparse Attention -> # of sampling Key and Query
    n_head: 4 # Use it Attention Graph Learning
    dropout_rate: 0.5
    pre_mlp_layer: [64, 32]

forecasting_module:
    name: pn_beats
    stack_num: 3
    singular_stack_num: 1
    inter_correlation_block_type: MPGLU # GCN, MPNN, MPGLU, MP_single_message, MPGLU_single_message
    activ: ReLU
    inter_correlation_stack_length: 1
    forecast_length: 12
    backcast_length: 12
    n_theta_hidden: [8, 8]
    thetas_dim: [8, 8]
    message_norm: True
    share_weights_in_stack: True
    pooling_mode: average
    n_pool_kernel_size: [4, 4, 2]
    n_stride_size : [2, 2, 1]
