---
exp_name: 0517_N_BEATS # 0417
exp_dir: ../exp
use_gpu: False
device: cpu
seed: None # If you want to reproduce set the seed that you want
model_name: N_BEATS_generic  # GTS_Top_k_Masking_model, ...
train_resume: False

dataset:
    root: ./data/METR-LA
    name: METR-LA
    nodes_num: 207
    node_features: 2
    graph_learning_length: 34272
    scaler_type: std # std, invariant, norm, norm1, median

train:
    optimizer: Adam
    epoch: 2
    loss_function : MAE
    backcast_loss: False
    lr: 1.0e-3
    wd: 0.0e-4 # Adam
    momentum: 0.9 # SGD
    T_0: 50 # cosine annealing
    T_mult: 5 # cosine annealing
    batch_size : 128

graph_learning:
    mode: None # GTS, attention, MTGNN, GDN, None
    graph_mode: ground_truth # no_graph, ground_truth, random_graph It use when graph learning mode is None
    edge_prob: 0.01 # Use this probability when graph_mode is random_graph

    sampling: None # Gumbel_softmax, Top_K_Masking, Top_K, Weight, None
    tau: 10 # Gumbel softmax tau
    top_k: 10
    alpha: 200 # Use as threshold at tanh
    to_symmetric: False
    initial_edge_index: Fully Connected
    sequence: 1 # make graph learning module sequential

    kernel_size: [10, 10]
    stride: [1, 1]
    conv_dim: [8, 16]
    n_head: 4 # Use it Attention Graph Learning
    hidden_dim: 128


forecasting_module:
    name: n_beats
    stack_types: [n_hits] # seasonality, trend, generic, n_hits
    inter_correlation_block_type: MPGLU # GCN, MPNN, MPGLU, MP_single_message, MPGLU_single_message
    activ: 'ReLU'
    num_blocks_per_stack: 1
    inter_correlation_stack_length: 1
    forecast_length: 12
    backcast_length: 60
    n_theta_hidden: [8, 8]
    thetas_dim: [8, 8]
    message_norm: True
    share_weights_in_stack: True
    pooling_mode: max
    n_pool_kernel_size: 5
    device: cpu