---
exp_name: test
exp_dir: ./exp
use_gpu: False
device: cpu
seed: 1010
model_name: GTS

dataset:
  root: ./data/CCN/monkey_spike.pickle
  name: monkey_data
  total_time_length: 742
  window_size: 202
  slide: 54
  train_valid_test: [80,90,100]

#  time_steps: 10
#  pred_steps: 2
#  window: 100
#  train_step: 400
#  validation_step: 440
#  test_step: 480


train:
  optimizer: Adam
  epoch: 2
  loss_function : MSELoss
  lr: 1.0e-3
  momentum: 0.9
  wd: 0.0e-4
  batch_size : 1
  lr_decay: 0.1
  lr_decay_steps: [10000]

decode_step: 54
decode_dim: 3

node_features: 1
output_dim: 3
nodes_num: 98

kernel_size: [100, 50, 10]
stride: [10, 5, 1]
conv1_dim: 16
conv2_dim: 64
hidden_dim: 128

diffusion_k: 3
num_layer: 1

embedding:
  kernel_size: [20, 10]
  stride: [5, 3]
  conv_dim: 16
  embedding_dim: 64


