---
exp_name: dgx_1
exp_dir: ./exp/0121/both/sigmoid
use_gpu: True
device: 0
seed: 10106

model_name: GTS

graph_learning_module: GTS
graph_forecasting_module: GTS
initial_edge_index: Fully Connected

dataset:
  root: ./data/spike_lambda_bin100
  name: spike_lambda_bin100
  graph_learning_length: 48000
  idx_ratio: 0.5
  window_size: 200
  slide: 10
  pred_step: 10

  train_valid_test: [4000000,4400000,4800000]
  save: ./data/spike_lambda_bin100/


train:
  optimizer: Adam
  epoch: 200
#  loss_function : MSELoss
  lr: 1.0e-3
  momentum: 0.9
  wd: 0.0e-4
  batch_size : 32
  lr_decay: 0.1
  lr_decay_steps: [10000]

nodes_num: 100
node_features: 1
hidden_dim: 128
embedding_dim: 64

graph_learning:
  sequence: 1
  mode: both # adj
  to_symmetric: True
  kernel_size: [200, 100, 50]
  stride: [20, 10, 5]
  conv1_dim: 16
  conv2_dim: 32
  conv3_dim: 64
#  fc_dim: 256


forecasting_module:
  diffusion_k: 1
  num_layer: 1
  use_teacher_forcing: True
  teacher_forcing_ratio: 0.5

  embedding:
    kernel_size: [50, 5]
    stride: [5, 2]
    conv1_dim: 16
    conv2_dim: 32
#    fc_dim: 128

encoder_step: 10
decoder_step: 3

tau: 0.3



