dataset:
  graph_learning_length: 4800
  idx_ratio: 0.5
  name: spike_lambda_bin100
  pred_step: 5
  root: ./data/spike_lambda_bin100
  save: ./data/spike_lambda_bin100/
  slide: 5
  train_valid_test:
  - 4000
  - 4400
  - 4800
  window_size: 20
decoder_step: 2
device: cpu
embedding_dim: 16
encoder_step: 2
exp_dir: ./exp\GTS_1_0222_020332
exp_name: GTS_1_0222_020332
forecasting_module:
  diffusion_k: 1
  embedding:
    conv1_dim: 2
    conv2_dim: 2
    kernel_size:
    - 3
    - 3
    stride:
    - 1
    - 1
  num_layer: 1
  teacher_forcing_ratio: 0.5
  use_teacher_forcing: true
graph_forecasting_module: GTS
graph_learning:
  conv1_dim: 4
  conv2_dim: 4
  conv3_dim: 4
  correlation_act_fnc: sigmoid
  kernel_size:
  - 200
  - 80
  - 10
  mode: attention
  n_head: 16
  sequence: 3
  stride:
  - 20
  - 10
  - 5
  to_symmetric: true
graph_learning_module: GTS
hidden_dim: 16
initial_edge_index: Fully Connected
model_name: GTS
model_save: ./exp\GTS_1_0222_020332\model_save
node_features: 1
nodes_num: 100
seed: 1010
tau: 0.3
train:
  batch_size: 2
  epoch: 2
  loss_function: MSELoss
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  momentum: 0.9
  optimizer: Adam
  wd: 0.0
use_gpu: false
